server:
  port: 8081

spring:
  application:
    name : eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}