server:
  port: 8082


spring:
  application:
    name: eureka-client-consumer
eureka:
  client:
    service-url:
      defaultZone: http://test:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2