server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  dashboard:
    path: /eurekawebui
#  server:
#    enable-self-preservation: false
security:
  basic:
    enabled: true
  user:
    name: test
    password: 123456
