server:
  port: 8085
spring:
  application:
    name: feign-consumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://test:123456@localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


